CREATE TABLE rooms (
                       room_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY ,
                       name VARCHAR2(100) NOT NULL,
                       location VARCHAR2(100),
                       capacity NUMBER
);

CREATE TABLE users (
                       user_id VARCHAR2(50) PRIMARY KEY,
                       role VARCHAR2(20)
);

CREATE TABLE reservations (
                              reservation_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                              room_id NUMBER NOT NULL,
                              user_id VARCHAR2(50) NOT NULL,
                              start_at TIMESTAMP NOT NULL,
                              end_at TIMESTAMP NOT NULL,
                              CONSTRAINT fk_room FOREIGN KEY(room_id) REFERENCES rooms(room_id),
                              CONSTRAINT fk_user FOREIGN KEY(user_id) REFERENCES users(user_id)
);
